# Generated by Django 3.2.3 on 2021-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('status_choice', models.CharField(choices=[('AP', 'Approved'), ('MO', 'Moderation'), ('RJ', 'Rejected')], default='AP', max_length=2)),
            ],
        ),
    ]
